LOCATIONS = {
    { "@Abandoned A/Cube Bit" },
    { "@Abandoned B/Cube Bit" },
    { "@Ancient Walls/Cube Bit 1" },
    { "@Ancient Walls/Cube Bit 2" },
    { "@Ancient Walls/Cube Bit 3" },
    { "@Arch/Cube Bit 1" },
    { "@Arch/Cube Bit 2" },
    { "@Arch/Cube Bit 3" },
    { "@Bell Tower/Cube Bit 1" },
    { "@Bell Tower/Cube Bit 2" },
    { "@Big Owl/Cube Bit" },
    { "@Big Tower/Cube Bit 1" },
    { "@Big Tower/Cube Bit 2" },
    { "@Big Tower/Cube Bit 3" },
    { "@Big Tower/Cube Bit 4" },
    { "@Big Tower/Cube Bit 5" },
    { "@Big Tower/Cube Bit 6" },
    { "@Big Tower/Cube Bit 7" },
    { "@Big Tower/Cube Bit 8" },
    { "@Extractor A/Cube Bit" },
    { "@Five Towers/Cube Bit 1" },
    { "@Five Towers/Cube Bit 2" },
    { "@Five Towers/Cube Bit 3" },
    { "@Fox/Cube Bit" },
    { "@Fractal/Cube Bit 1" },
    { "@Fractal/Cube Bit 2" },
    { "@Fractal/Cube Bit 3" },
    { "@Globe/Cube Bit" },
    { "@Graveyard A/Cube Bit 1" },
    { "@Graveyard A/Cube Bit 2" },
    { "@Graveyard A/Cube Bit 3" },
    { "@Graveyard Gate/Cube Bit 1" },
    { "@Graveyard Gate/Cube Bit 2" },
    { "@Graveyard Gate/Cube Bit 3" },
    { "@Graveyard Gate/Cube Bit 4" },
    { "@Graveyard Gate/Cube Bit 5" },
    { "@Graveyard Gate/Cube Bit 6" },
    { "@Graveyard Gate/Cube Bit 7" },
    { "@Grave Cabin/Cube Bit 1" },
    { "@Grave Cabin/Cube Bit 2" },
    { "@Grave Ghost/Cube Bit 1" },
    { "@Grave Ghost/Cube Bit 2" },
    { "@Grave Lesser Gate/Cube Bit" },
    { "@Grave Treasure A/Cube Bit 1" },
    { "@Grave Treasure A/Cube Bit 2" },
    { "@Industrial Superspin/Cube Bit 1" },
    { "@Industrial Superspin/Cube Bit 2" },
    { "@Industrial Superspin/Cube Bit 3" },
    { "@Indust Abandoned A/Cube Bit" },
    { "@Kitchen/Cube Bit" },
    { "@Lighthouse/Cube Bit 1" },
    { "@Lighthouse/Cube Bit 2" },
    { "@Lighthouse House A/Cube Bit" },
    { "@Lighthouse Spin/Cube Bit" },
    { "@Mausoleum/Cube Bit 1" },
    { "@Mausoleum/Cube Bit 2" },
    { "@Mausoleum/Cube Bit 3" },
    { "@Mausoleum/Cube Bit 4" },
    { "@Mine A/Cube Bit" },
    { "@Mine Bomb Pillar/Cube Bit" },
    { "@Mine Wrap/Cube Bit 1" },
    { "@Mine Wrap/Cube Bit 2" },
    { "@Nature Hub/Cube Bit 1" },
    { "@Nature Hub/Cube Bit 2" },
    { "@Nu Zu Abandoned A/Cube Bit" },
    { "@Nu Zu Abandoned B/Cube Bit" },
    { "@Oldschool/Cube Bit" },
    { "@Oldschool Ruins/Cube Bit" },
    { "@Owl/Cube Bit" },
    { "@Pivot One/Cube Bit 1" },
    { "@Pivot One/Cube Bit 2" },
    { "@Pivot One/Cube Bit 3" },
    { "@Pivot Two/Cube Bit 1" },
    { "@Pivot Two/Cube Bit 2" },
    { "@Pivot Two/Cube Bit 3" },
    { "@Pivot Watertower/Cube Bit" },
    { "@Purple Lodge Ruin/Cube Bit" },
    { "@School/Cube Bit" },
    { "@Sewer Fork/Cube Bit" },
    { "@Sewer Geyser/Cube Bit" },
    { "@Sewer Hub/Cube Bit 1" },
    { "@Sewer Hub/Cube Bit 2" },
    { "@Sewer Pillars/Cube Bit 1" },
    { "@Sewer Pillars/Cube Bit 2" },
    { "@Sewer Pillars/Cube Bit 3" },
    { "@Sewer Pivot/Cube Bit" },
    { "@Sewer QR/Cube Bit" },
    { "@Sewer Start/Cube Bit" },
    { "@Sewer to Lava/Cube Bit" },
    { "@Showers/Cube Bit" },
    { "@Skull/Cube Bit 1" },
    { "@Skull/Cube Bit 2" },
    { "@Skull/Cube Bit 3" },
    { "@Spinning Plates/Cube Bit" },
    { "@Stargate Ruins/Cube Bit 1" },
    { "@Stargate Ruins/Cube Bit 2" },
    { "@Throne/Cube Bit" },
    { "@Tree Crumble/Cube Bit" },
    { "@Triple Pivot Cave/Cube Bit 1" },
    { "@Triple Pivot Cave/Cube Bit 2" },
    { "@Two Walls/Cube Bit 1" },
    { "@Two Walls/Cube Bit 2" },
    { "@Two Walls/Cube Bit 3" },
    { "@Villageville/Cube Bit 1" },
    { "@Villageville/Cube Bit 2" },
    { "@Villageville/Cube Bit 3" },
    { "@Villageville/Cube Bit 4" },
    { "@Wall Hole/Cube Bit 1" },
    { "@Wall Hole/Cube Bit 2" },
    { "@Wall Interior A/Cube Bit" },
    { "@Wall Kitchen/Cube Bit" },
    { "@Wall School/Cube Bit" },
    { "@Wall Village/Cube Bit" },
    { "@Waterfall/Cube Bit" },
    { "@Weightswitch Temple/Cube Bit 1" },
    { "@Weightswitch Temple/Cube Bit 2" },
    { "@Windmill Cave/Cube Bit" },
    { "@Zu Bridge/Cube Bit 1" },
    { "@Zu Bridge/Cube Bit 2" },
    { "@Zu City/Cube Bit 1" },
    { "@Zu City/Cube Bit 2" },
    { "@Zu Code Loop/Cube Bit 1" },
    { "@Zu Code Loop/Cube Bit 2" },
    { "@Zu House Empty/Cube Bit" },
    { "@Zu House Ruin Visitors/Cube Bit" },
    { "@Zu House Scaffolding/Cube Bit" },
    { "@Zu Library/Cube Bit" },
    { "@Zu Throne Ruins/Cube Bit" },
    { "@Clock/Golden Cube" },
    { "@Five Towers/Golden Cube" },
    { "@Grave Lesser Gate/Golden Cube" },
    { "@Grave Treasure A/Golden Cube" },
    { "@Mine Wrap/Golden Cube" },
    { "@Observatory/Golden Cube" },
    { "@Pivot Three/Golden Cube" },
    { "@Sewer Lesser Gate B/Golden Cube" },
    { "@Spinning Plates/Golden Cube" },
    { "@Superspin Cave/Golden Cube" },
    { "@Two Walls/Golden Cube" },
    { "@Visitor/Golden Cube" },
    { "@Zu Code Loop/Golden Cube" },
    { "@Zu Switch B/Golden Cube" },
    { "@Others/Achievement Anti-Cube\nRT RT LT RT RT LT LT LT" },
    { "@Clock/Minute Anti-Cube" },
    { "@Clock/Hour Anti-Cube" },
    { "@Clock/Day Anti-Cube" },
    { "@Clock/Week Anti-Cube" },
    { "@CMY Fork/Anti-Cube\nLT RT RT RT LT RT RT LT" },
    { "@Lava Fork/Anti-Cube\nLT LT RT LT LT RT RT RT" },
    { "@Sewer Fork/Anti-Cube\nLT LT LT RT LT RT LT RT" },
    { "@Zu Fork/Anti-Cube\nLT RT RT LT LT LT RT RT RT RT" },
    { "@Lighthouse/Anti-Cube\nUp LT RT Up LT Up RT Up" },
    { "@Tree/Anti-Cube\nRight RT Left LT Left Up Down A" },
    { "@Tree Sky/Anti-Cube\nLT A RT Up Down LT RT A" },
    { "@Zu Bridge/Anti-Cube\nLeft Left Down Down Right Right Up Up" },
    { "@Bell Tower/Anti-Cube" },
    { "@Quantum/Anti-Cube" },
    { "@Watertower Secret/Anti-Cube\nRT RT RT LT RT RT RT LT" },
    { "@Zu Code Loop/Anti-Cube\nRight LT Right A RT Down A Up" },
    { "@CMY B/Anti-Cube" },
    { "@Zu Tetris/Anti-Cube" },
    { "@Lava Skull/Anti-Cube" },
    { "@Big Owl/Anti-Cube" },
    { "@Skull B/Anti-Cube" },
    { "@Telescope/Anti-Cube\nRight RT Left RT RT A A Right" },
    { "@Zu House QR/Anti-Cube\nRT RT LT RT LT LT LT RT" },
    { "@Zu Unfold/Anti-Cube\n▀ ▀ █ ▄ ▄" },
    { "@Code Machine/Anti-Cube\nUp A RT LT A Down LT RT" },
    { "@Parlor/Anti-Cube\nRT RT LT RT LT LT LT RT" },
    { "@Boileroom/Anti-Cube\nUp RT Left A Right LT Down RT" },
    { "@Nu Zu School/Anti-Cube\nUp Left RT A LT Right A Down" },
    { "@Zu Heads/Anti-Cube" },
    { "@Sewer QR/Throne Anti-Cube\r\nRT RT LT RT RT RT LT LT\r\nRT LT LT LT RT LT RT LT" },
    { "@Ritual/Black Monolith\nUp RT Up A Down LT Up Down\n\nHeart Cube\nDown Down LT RT RT A Up" },
    { "@Telescope/Telescope Heart Cube\nRT LT LT RT RT LT" },
    { "@Zu Zuish/Security Question Heart Cube" },
    { "@Arch/Chest 1" },
    { "@Arch/Chest 2" },
    { "@Five Towers Cave/Chest" },
    { "@Fox/Chest" },
    { "@Globe Int/Chest" },
    { "@Industrial Superspin/Chest" },
    { "@Lighthouse House A/Chest" },
    { "@Mausoleum/Chest" },
    { "@Mine Bomb Pillar/Chest" },
    { "@Orrery B/Chest" },
    { "@Parlor/Chest" },
    { "@Pivot Watertower/Chest" },
    { "@Sewer Pivot/Chest" },
    { "@Sewer Treasure One/Chest" },
    { "@Sewer Treasure Two/Chest" },
    { "@Tree Crumble/Chest" },
    { "@Tree of Death/Chest" },
    { "@Tree Sky/Chest" },
    { "@Villageville/Chest" },
    { "@Wall Hole/Chest" },
    { "@Water Wheel B/Chest" },
    { "@Windmill Cave/Chest" },
    { "@Zu City Ruins/Chest" },
    { "@Zu House Empty B/Chest" },
    { "@Waterfall/Owl" },
    { "@Visitor/Owl" },
    { "@Pivot One/Owl" },
    { "@Tree/Owl" },
    { "@Boileroom/Map"},
}

LOCATIONS_MAPPING = {}
for n, item in ipairs(LOCATIONS) do
    LOCATIONS_MAPPING[0xFE500 + n - 1] = item
end
